dist: trusty
language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libwavpack-dev libpulse-dev python3 python3-pyside check libsndfile1-dev libsamplerate0-dev
  - ./get_build_support.sh
  - gcc --version
  - clang --version
script:
  - ./make.py --enable-long-tests
  - ./make.py --enable-long-tests --cc=clang
